site_name:        ManualScraper.jl
repo_url:         https://github.com/ajkeller34/ManualScraper.jl
site_description: Package for scraping instrument manuals to assemble standardized templates of commands and documentation.
site_author:      Andrew Keller

theme: material
extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- License: LICENSE.md
